### ISSUE TITLE
Marker setDrawable

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#1156]
wheh I call function setDrawable, I have exception 

> java.lang.ArrayIndexOutOfBoundsException: length=1152; index=1152

**Comment by tallytalwar** [comment]
Can you post more stack from the logs?

Also are you using the very latest release? https://github.com/tangrams/tangram-es/releases/tag/0.4.6-android

**Comment by ivangorelow** [comment]
yes, I use 0.4.6

> Process: com.impulsm.mobileclientcodd, PID: 10465
                  java.lang.ArrayIndexOutOfBoundsException: length=512; index=512
                      at com.mapzen.tangram.Marker.setBitmap(Marker.java:188)
                      at com.mapzen.tangram.Marker.setDrawable(Marker.java:72)
                      at com.impulsm.mobileclientcodd.controllers.MapViewController.addMarkers(MapViewController.java:388)
                      at com.impulsm.mobileclientcodd.controllers.MapViewController.access$2000(MapViewController.java:85)
                      at com.impulsm.mobileclientcodd.controllers.MapViewController$3.onMapReady(MapViewController.java:307)
                      at com.mapzen.tangram.MapView$1.onPostExecute(MapView.java:77)
                      at com.mapzen.tangram.MapView$1.onPostExecute(MapView.java:62)
                      at android.os.AsyncTask.finish(AsyncTask.java:636)
                      at android.os.AsyncTask.access$500(AsyncTask.java:177)
                      at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5254)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by ivangorelow** [comment]
your function works only with square drawable

**Comment by tallytalwar** [comment]
Yup, was a typo in the code. Should be fixed by #1157. Will probably cut a patched release today.
