### ISSUE TITLE
build the "library" and "demo" on windows

### ISSUE THREAD

**Issue by TGISer** [tangrams/tangram-es#1351]
I open the project in Android Studio and press the 'Run' button (^R). 

Error:A problem occurred configuring project ':demo'.
> Could not resolve all dependencies for configuration ':demo:_debugApk'.
   > A problem occurred configuring project ':tangram'.
      > executing external native build for cmake E:\AndroidStudioProjects\tangram-es-0.5.0-android\CMakeLists.txt

How can i solve the error ,thank you for your help!

**Comment by tallytalwar** [comment]
Hi @TGISer 

We have tested and support android builds on windows 10. What windows are you using?

Also, did you `init` and `update` the submodules? Try doing the following:
1. After cloning the project, run: `git submodule update --init`
2. In your already created android studio project, sync gradle again for it to pick up the changes from the submodules.

If this does not work, can you post your steps you did to get to the above mentioned error?

Thanks

**Comment by TGISer** [comment]
@tallytalwar 
I use windows 10.

1. git clone https://github.com/tangrams/tangram-es.git
2. git submodule update --init --recursive
3. open the project in Android Studio and press the 'Run' button (^R).

**Comment by TGISer** [comment]
@tallytalwar 
I can do it now ! But when I run demo 


D/dalvikvm: Trying to load lib /data/data/com.mapzen.tangram.android/lib/libtangram.so 0x41723fe0
 W/dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/mapzen/tangram/MapController;
 D/AndroidRuntime: Shutting down VM
 W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x40aae210)
 E/AndroidRuntime: FATAL EXCEPTION: main
 java.lang.ExceptionInInitializerError
 at com.mapzen.tangram.MapView.getMapInstance(MapView.java:107)
 at com.mapzen.tangram.MapView.getMapAsync(MapView.java:77)
 at com.mapzen.tangram.MapView.getMapAsync(MapView.java:61)
 at com.mapzen.tangram.android.MainActivity.onCreate(MainActivity.java:57)
 at android.app.Activity.performCreate(Activity.java:4465)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1931)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1992)
 at android.app.ActivityThread.access$600(ActivityThread.java:127)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1158)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:4441)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:823)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:590)
 at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: link_image[1936]: 156 could not load needed library 'libc++_shared.so' for 'libtangram.so' (load_library[1091]: Library 'libc++_shared.so' not found)
 at java.lang.Runtime.loadLibrary(Runtime.java:370)
 at java.lang.System.loadLibrary(System.java:535)
 at com.mapzen.tangram.MapController.(MapController.java:962)
 at com.mapzen.tangram.MapView.getMapInstance(MapView.java:107) 
 at com.mapzen.tangram.MapView.getMapAsync(MapView.java:77) 
 at com.mapzen.tangram.MapView.getMapAsync(MapView.java:61) 
 at com.mapzen.tangram.android.MainActivity.onCreate(MainActivity.java:57) 
 at android.app.Activity.performCreate(Activity.java:4465) 
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049) 
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1931) 
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1992) 
 at android.app.ActivityThread.access$600(ActivityThread.java:127) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1158) 
 at android.os.Handler.dispatchMessage(Handler.java:99) 
 at android.os.Looper.loop(Looper.java:137) 
 at android.app.ActivityThread.main(ActivityThread.java:4441) 
 at java.lang.reflect.Method.invokeNative(Native Method) 
 at java.lang.reflect.Method.invoke(Method.java:511) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:823) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:590) 
 at dalvik.system.NativeStart.main(Native Method)

**Comment by matteblair** [comment]
@TGISer did you change anything or take any different steps to get the build working?

**Comment by TGISer** [comment]
@matteblair 
git submodule update --init --recursive
It doesn't work ，so  I download submodule by myself.

**Comment by matteblair** [comment]
In the latest revision of tangram-es, there is actually no need for recursive submodules. `git submodule update --init` should be sufficient. It will be easiest to remove the code you manually downloaded and let git handle the submodules.

**Comment by TGISer** [comment]
@matteblair 
It doesn't work and have the error.

Then I try only build the "demo"

I replace
dependencies {
  compile project(path: ':tangram')
}

dependencies {
  compile 'com.mapzen.tangram:tangram:0.5.0'
}

but it have the same error .

**Comment by matteblair** [comment]
Can you try installing and running http://android.mapzen.com/tangram-latest.apk

If this crashes on your phone, please share the logcat output.

**Comment by TGISer** [comment]
@matteblair 
What is the minimum version of Android?

**Comment by matteblair** [comment]
The minimum API level is 15 (Android 4.0.3)

**Comment by TGISer** [comment]
I try installing and running http://android.mapzen.com/tangram-latest.apk on my phone(Android 4.0.4)
it crashe .

But it can run on other devices.

Can you give me thr IOS version of the URL like http://android.mapzen.com/tangram-latest.apk.

Thank you !

**Comment by matteblair** [comment]
Interesting! Can you post the logcat output of the crash from your device running 4.0.4?

iOS apps aren't as simple to distribute as Android apps, we have to register a device ID before anything can be installed.

**Comment by matteblair** [comment]
This should be resolved by https://github.com/tangrams/tangram-es/pull/1389

**Comment by tallytalwar** [comment]
Marking this resolved, as #1389 went in 0.6.0  release. Kindly reopen if you still have questions on the same. Thanks
