### ISSUE TITLE
run "android demo" on windows 10 error

### ISSUE THREAD

**Issue by TGISer** [tangrams/tangram-es#1357]
D/dalvikvm: Trying to load lib /data/data/com.mapzen.tangram.android/lib/libtangram.so 0x41723fe0
W/dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/mapzen/tangram/MapController;
D/AndroidRuntime: Shutting down VM
W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x40aae210)
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.ExceptionInInitializerError
                      at com.mapzen.tangram.MapView.getMapInstance(MapView.java:107)
                      at com.mapzen.tangram.MapView.getMapAsync(MapView.java:77)
                      at com.mapzen.tangram.MapView.getMapAsync(MapView.java:61)
                      at com.mapzen.tangram.android.MainActivity.onCreate(MainActivity.java:57)
                      at android.app.Activity.performCreate(Activity.java:4465)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1931)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1992)
                      at android.app.ActivityThread.access$600(ActivityThread.java:127)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1158)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:137)
                      at android.app.ActivityThread.main(ActivityThread.java:4441)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:511)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:823)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:590)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: link_image[1936]:   156 could not load needed library 'libc++_shared.so' for 'libtangram.so' (load_library[1091]: Library 'libc++_shared.so' not found)
                      at java.lang.Runtime.loadLibrary(Runtime.java:370)
                      at java.lang.System.loadLibrary(System.java:535)
                      at com.mapzen.tangram.MapController.<clinit>(MapController.java:962)
                      at com.mapzen.tangram.MapView.getMapInstance(MapView.java:107) 
                      at com.mapzen.tangram.MapView.getMapAsync(MapView.java:77) 
                      at com.mapzen.tangram.MapView.getMapAsync(MapView.java:61) 
                      at com.mapzen.tangram.android.MainActivity.onCreate(MainActivity.java:57) 
                      at android.app.Activity.performCreate(Activity.java:4465) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1931) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1992) 
                      at android.app.ActivityThread.access$600(ActivityThread.java:127) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1158) 
                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                      at android.os.Looper.loop(Looper.java:137) 
                      at android.app.ActivityThread.main(ActivityThread.java:4441) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:511) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:823) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:590) 
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by matteblair** [comment]
We'll keep this in https://github.com/tangrams/tangram-es/issues/1351, to keep the context clear.
