### ISSUE TITLE
OutOfMemoryError crash report

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1671]
I got the following crash report from one of my users. Is this of any value for you? Otherwise, feel free to close it.

Using tangram-ES 0.8.0.

```
Device: Motorola osprey_u2, Android 7.1.2
Thread: OkHttp Dispatcher
App version: 2.0
Stack trace:
java.lang.OutOfMemoryError: Failed to allocate a 8204 byte allocation with 9270504 free bytes and 8MB until OOM; failed due to fragmentation (required continguous free 12288 bytes where largest contiguous free 8192 bytes)
at okio.Segment.<init>(Segment.java:61)
at okio.SegmentPool.take(SegmentPool.java:46)
at okio.Buffer.writableSegment(Buffer.java:1160)
at okio.InflaterSource.read(InflaterSource.java:66)
at okio.GzipSource.read(GzipSource.java:80)
at okio.Buffer.writeAll(Buffer.java:996)
at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:106)
at okhttp3.ResponseBody.bytes(ResponseBody.java:135)
at com.mapzen.tangram.MapController$13.onResponse(MapController.java:1339)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
```

**Comment by matteblair** [comment]
Hmmm we don't often see OOM errors! However in 0.8.1 we did fix a bug that was hogging huge amounts of memory. I suspect this might be due to that previous bug. If this becomes a pattern then re-open this issue and add any more reports you receive. Thanks!

**Comment by westnordost** [comment]
This was also the first one I saw whatsoever.
