### ISSUE TITLE
Android: Crash on startup (Replicant OS, no hardware acceleration)

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1908]
A user of StreetComplete reported that the app crashes on startup. 

Device: Samsung S3
OS: Replicant OS 
(see https://tehnoetic.com/mobile-devices/tehnoetic-s3-phone-replicant ) 

Replicant OS on that phone has no hardware graphics acceleration.

Here is the log:
```
[10-22 09:05:46.850 25727:25753 D/libEGL]
Emulator without GPU support detected. Fallback to software renderer.

[10-22 09:05:46.980 25727:25753 D/libEGL]
loaded /system/lib/egl/libGLES_android.so

[10-22 09:05:47.085 13056:13099 I/ActivityManager]
Displayed de.westnordost.streetcomplete/.MainActivity: +3s87ms

[10-22 09:05:47.105 25727:25753 E/AndroidRuntime]
FATAL EXCEPTION: GLThread 863
Process: de.westnordost.streetcomplete, PID: 25727
Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
java.lang.IllegalArgumentException: No configs match configSpec
	at com.mapzen.tangram.ConfigChooser.chooseConfig(ConfigChooser.java:61)
	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1024)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

[10-22 09:05:47.105 13056:13179 W/ActivityManager]
  Force finishing activity de.westnordost.streetcomplete/.MainActivity

[10-22 09:05:47.295 1914:1914 D/gralloc]
Registering a buffer in the process that created it. This may cause memory ordering problems.

[10-22 09:05:47.295 1914:1914 E/libEGL]
called unimplemented OpenGL ES API

[10-22 09:05:47.295 1914:1914 E/SurfaceFlinger]
glCheckFramebufferStatusOES error -1702249345

[10-22 09:05:47.295 1914:1914 E/SurfaceFlinger]
got GL_FRAMEBUFFER_COMPLETE_OES error while taking screenshot
```

I'll ask the person to try some OpenGL demo app from F-Droid or such to exclude that this is actually an issue of Replicant OS and report his findings here.

**Comment by westnordost** [comment]
The user tried another app that apparently uses OpenGL (IceCat), but it seems that this crashes for a reason other than _"called unimplemented OpenGL ES API"_.

**Comment by matteblair** [comment]
The thing that's crashing on this device is Tangram's code to set up the GL rendering environment, starting with: `java.lang.IllegalArgumentException: No configs match configSpec`. That line means we asked for a set of GL configurations with at least our bare minimum requirements and the device returned none. Either there's a bug in libEGL on this device or it's just not capable of running a GLES2 application.
