### ISSUE TITLE
Crash on disposing map (0.12.0)

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#2136]
On tangram-es 0.12.0, on Android Lollipop, I get the following crash report. I can reliably reproduce it by just ending the app.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapzen.tangram.MapData.remove()' on a null object reference
        at com.mapzen.tangram.MapController.dispose(MapController.java:220)
```

Don't ask me how this can ever be null. Looking at the Java code, it doesn't look like this is possible.

(For completeness sake, here is the full stacktrace:)
```
01-23 16:01:04.912 24835-24835/de.westnordost.streetcomplete.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.westnordost.streetcomplete.debug, PID: 24835
    java.lang.RuntimeException: Unable to destroy activity {de.westnordost.streetcomplete.debug/de.westnordost.streetcomplete.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapzen.tangram.MapData.remove()' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3812)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3830)
        at android.app.ActivityThread.access$1400(ActivityThread.java:156)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:211)
        at android.app.ActivityThread.main(ActivityThread.java:5389)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapzen.tangram.MapData.remove()' on a null object reference
        at com.mapzen.tangram.MapController.dispose(MapController.java:220)
        at com.mapzen.tangram.MapView.disposeMap(MapView.java:262)
        at com.mapzen.tangram.MapView.onDestroy(MapView.java:312)
        at de.westnordost.streetcomplete.map.MapFragment.onDestroy(MapFragment.kt:94)
        at de.westnordost.streetcomplete.map.LocationAwareMapFragment.onDestroy(LocationAwareMapFragment.kt:97)
        at de.westnordost.streetcomplete.map.QuestsMapFragment.onDestroy(QuestsMapFragment.kt:84)
        at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2830)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1028)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2644)
        at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2825)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1028)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2644)
        at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:329)
        at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:366)
        at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:233)
        at android.app.Activity.performDestroy(Activity.java:6169)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1141)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3799)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3830) 
        at android.app.ActivityThread.access$1400(ActivityThread.java:156) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:211) 
        at android.app.ActivityThread.main(ActivityThread.java:5389) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) 
```

**Comment by matteblair** [comment]
Huh. This really does look like it should be impossible. Maybe a result of a race condition where `clientTileSources` is concurrently modified? But if this occurs repeatably then that isn't consistent with a race condition...

Did this only start happening with version 0.12?

**Comment by westnordost** [comment]
I can reproduce this with 0.11.2 as well.

**Comment by tallytalwar** [comment]
I just like the sound of this :). assigning to me.

**Comment by westnordost** [comment]
I was not able to always reliably reproduce it, sometimes it crashed on exit, sometimes not.

However I now see a few crash reports on Google Play now, so it is not some issue that only occurs for debug builds or the like. The crash reports I see are with Android 9 devices, so it is also not specific to a certain Android version.

**Comment by westnordost** [comment]
This unfortunately still exists. I put it in a big try-catch, but if I hadn't, the app would crash all the time.

**Comment by matteblair** [comment]
I've fixed this issue in https://github.com/tangrams/tangram-es/pull/2223 because I believe it might be related to the segfault I was trying to fix there. 

The problem here is a little subtle. In `MapController.dispose()` we iterate over `clientTileSources.values()` and for each `MapData` value we call `MapData.remove()`, which then calls `MapController.removeDataLayer(MapData)`, which then removes the `MapData` entry from `clientTileSources`. So we are modifying the `clientTileSources` Map *while* we are iterating over the Map's value collection. As stated in the [Map.values() documentation](https://developer.android.com/reference/java/util/Map#values()), this is a no-no. 

The fix for this was to refactor `dispose()` and `remove()` so that `MapController` can dispose the `MapData` entries in a loop without modifying the collection: https://github.com/tangrams/tangram-es/pull/2223/commits/2ac49fb587343d8fe8615f171355363d44933a73
