### ISSUE TITLE
NullPointerException in NativeMap.updateCameraPosition

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#2263]
Since tangram 0.16.0, I am getting a lot of error reports like these 

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapzen.tangram.NativeMap.updateCameraPosition(int, double, double, float, float, float, float, float, float, double, double, double, double, android.graphics.Rect, float, int)' on a null object reference
at com.mapzen.tangram.MapController.updateCameraPosition(MapController.java:408)
at com.mapzen.tangram.MapController.updateCameraPosition(MapController.java:360)
at de.westnordost.streetcomplete.map.tangram.CameraManager.pushCameraPositionToController(CameraManager.kt:169)
at de.westnordost.streetcomplete.map.tangram.CameraManager.animate(CameraManager.kt:174)
at de.westnordost.streetcomplete.map.tangram.CameraManager.access$animate(CameraManager.kt:35)
at de.westnordost.streetcomplete.map.tangram.CameraManager$animateCameraUpdate$6.invoke(CameraManager.kt:157)
at de.westnordost.streetcomplete.map.tangram.CameraManager$animateCameraUpdate$6.invoke(CameraManager.kt:35)
at de.westnordost.streetcomplete.map.tangram.CameraManagerKt$sam$android_animation_ValueAnimator_AnimatorUpdateListener$0.onAnimationUpdate(Unknown Source:2)
at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:987)
at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1339)
at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1471)
at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1002)
at android.view.Choreographer.doCallbacks(Choreographer.java:816)
at android.view.Choreographer.doFrame(Choreographer.java:748)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:280)
at android.app.ActivityThread.main(ActivityThread.java:6706)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

So, some field in `MapController` is already null but it is still being accessed.

Maybe this has something to do with the following: The app uses the Android animation system to animate which repeatedly calls `updateCameraPosition` on the `MapController` during its course. On `onDestroy` however, all animations are cancelled, so after the Fragment/Activity has been destroyed, there should not be any calls anymore.

When does it occur? Not sure, it never occured to myself, I only get the crash reports. But I am pretty sure this happens when the view is being destroyed / recreated by app switch or something else.

**Comment by matteblair** [comment]
My first guess was that these animation callbacks might be on a background thread, but the stacktrace here looks like it's running on the main thread - so that rules out race conditions.

The `NativeMap` instance is disposed in the call to `MapView.onDestroy`, so these callbacks must be occurring after that point. Maybe you need to change the order in which objects get destroyed?

**Comment by westnordost** [comment]
The order in which onDestroy is called on fragments, activities and their lifecycle observers is nothing the individual app developer can influence. The order is given by the Android system. 

Am 12. Mai 2021 01:45:30 MESZ schrieb Matt Blair ***@***.***>:
>My first guess was that these animation callbacks might be on a
>background thread, but the stacktrace here looks like it's running on
>the main thread - so that rules out race conditions.
>
>The `NativeMap` instance is disposed in the call to
>`MapView.onDestroy`, so these callbacks must be occurring after that
>point. Maybe you need to change the order in which objects get
>destroyed?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tangrams/tangram-es/issues/2263#issuecomment-839291153

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by matteblair** [comment]
I looked at the StreetComplete code that seems to control these camera animations and I have a theory, so tell me if this makes sense:
- When OnDestroy is called on the MapFragment (and MapView) KtMapController calls cameraManager.cancelAllCameraAnimations() https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/map/tangram/KtMapController.kt#L133-L136
- In cancelAllCameraAnimations() a call to animator.cancel() is posted to the main thread Handler and not executed immediately https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/map/tangram/CameraManager.kt#L85-L94
- MapView.onDestroy finishes and the NativeMap instance is destroyed
- On the next main thread loop, the animators run their next step because cancel() has not been called yet, and the animation triggers the null pointer exception.

Does that seem plausible? If this is the case, you could test/fix it by making the animator.cancel() call directly on the main thread in the onDestroy callback.

**Comment by westnordost** [comment]
Wow, that's very cool that you did that!

- Correct
- Oh hmm, I think you are right. This might be the problem!
- Yes
- Right, yes this could be the source of this

I'll prepare a fix for this that. Since I could never reproduce this issue myself, I think I will just deploy the fix "into the blue" and then I'll see if I still get those crash reports or not. Shall we close this issue then until after I can report whether this was the issue or not?

**Comment by matteblair** [comment]
The StreetComplete code was pretty easy to navigate 👍 

I think it's better to close this issue, since there isn't any action to be taken in this repo. If the problem turns out to be something different, we can re-open the issue in the future.
