### ISSUE TITLE
Android: setContinuousRendering may be called before map init async task is finished

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#706]
If the scene file has any of the styles marked with `animate: true`, `Tangram::setScene()` calls `setContinuousRendering`, which for android will try to set `RenderMode` of the `MapView` which has not been initialized yet. Hence causing a `NullPointerException` on `android.opengl.GLSurfaceView.setRenderMode(int)`.

Log:
```
D/Tangram (17069): TANGRAM tangram.cpp:94: finish initialize
E/AndroidRuntime(17069): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(17069): Process: com.mapzen.tangram.android, PID: 17069
E/AndroidRuntime(17069): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(17069): 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
E/AndroidRuntime(17069): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(17069): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(17069): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(17069): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime(17069): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(17069): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(17069): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(17069): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.opengl.GLSurfaceView.setRenderMode(int)' on a null object reference
E/AndroidRuntime(17069): 	at com.mapzen.tangram.MapController.setRenderMode(MapController.java:410)
E/AndroidRuntime(17069): 	at com.mapzen.tangram.MapController.nativeInit(Native Method)
E/AndroidRuntime(17069): 	at com.mapzen.tangram.MapController.<init>(MapController.java:142)
E/AndroidRuntime(17069): 	at com.mapzen.tangram.MapController.getInstance(MapController.java:147)
E/AndroidRuntime(17069): 	at com.mapzen.tangram.MapView.getMapInstance(MapView.java:86)
E/AndroidRuntime(17069): 	at com.mapzen.tangram.MapView$1.doInBackground(MapView.java:70)
E/AndroidRuntime(17069): 	at com.mapzen.tangram.MapView$1.doInBackground(MapView.java:64)
E/AndroidRuntime(17069): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AndroidRuntime(17069): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(17069): 	... 4 more
```

Repro: Try to directly load the gotham style in the tangram-es android demo app.

**Comment by hjanetzek** [comment]
Yeah - One could pass GLSurfaceView to the MapController constructor I think

**Comment by tallytalwar** [comment]
Pushing a fix for this soon. You can check it and merge to master. I am never confident with my java implementation to directly put in master :|

**Comment by tallytalwar** [comment]
Here you go: https://github.com/tangrams/tangram-es/pull/707

**Comment by blair1618** [comment]
Rrrrr Ok, I think the only way to really solve this is to defer any calls to `setContinuousRendering` until after `setupGL()`. Even if we have a reference to the `GLSurfaceView` in the `MapController` constructor we can't safely make any calls on it from a background thread (i.e. during initialization).

**Comment by hjanetzek** [comment]
@blair1618 moving nativeInit to a separate function allows to create MapController to be initialized in advance. One init call must be done outside of the async task anyway to setup the TouchHandler
