### ISSUE TITLE
Android demo crashes

### ISSUE THREAD

**Issue by kkalera** [tangrams/tangram-es#775]
Hi everyone,

I was exploring the android demo but it keeps crashing when I launch it. I'm getting the following error;

> 06-04 15:39:12.084 7147-7147/com.mapzen.tangram.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.mapzen.tangram.android, PID: 7147
                                                                          java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.mapzen.tangram.android/files/instant-run/dex/slice-xmlpull-1.1.3.1_2ae060eca9b082620f63d2931128028997c84472-classes.dex", dex file "/data/data/com.mapzen.tangram.android/files/instant-run/dex/slice-support-annotations-23.1.1_b3b9cbcf0d9df078f68ccfab1e27355cef195378-classes.dex", dex file "/data/data/com.mapzen.tangram.android/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.mapzen.tangram.android/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.mapzen.tangram.android/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.mapzen.tangram.android/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.mapzen.tangram.android/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.mapzen.tangram.android/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.mapzen.tangram.android/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.mapzen.tangram.android/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.mapzen.tangram.android/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.mapzen.tangram.android/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.mapzen.tangram.android/files/instant-run/dex/slice-okio-1.6.0_3d247c033b3e2249bbfb78abe284e51be14663b1-classes.dex", dex file "/data/data/com.mapzen.tangram.android/files/instant-run/dex/slice-okhttp-2.5.0_b0f86d6030aa382e34835d0b979241aeeda0c7f6-classes.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib, /vendor/lib, /system/lib]]] couldn't find "libtangram.so"
                                                                              at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                              at java.lang.System.loadLibrary(System.java:988)
                                                                              at com.mapzen.tangram.MapController.<clinit>(MapController.java:616)
                                                                              at com.mapzen.tangram.MapView.getMapInstance(MapView.java:85)
                                                                              at com.mapzen.tangram.MapView.getMapAsync(MapView.java:63)
                                                                              at com.mapzen.tangram.android.MainActivity.onCreate(MainActivity.java:49)
                                                                              at android.app.Activity.performCreate(Activity.java:6072)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2315)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2424)
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:155)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:139)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5298)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
06-04 15:39:12.086 7147-7147/com.mapzen.tangram.android D/AppTracker: App Event: crash

Thank you for the help

**Comment by blair1618** [comment]
Hi @kkalera, thanks for the report. A couple of questions to help us out:

1. Are you building the demo app from source? What steps did you use?

2. What device are you trying to run on?

**Comment by kkalera** [comment]
Hi @blair1618 , thank you for coming back at me. 

I'm using android studio, and I imported the android folder from tangram-es-master. Then I try to run the demo app, but it crashes.

Currently trying to run it on a "oneplus x" api22 and have also tried it on a "nexus 6p" emulator api23. Same problem on both devices.

If you need any more information, I would be glad to help out.

**Comment by tallytalwar** [comment]
Hey @kkalera 

Did you build the native tangram library before running the tangram demo app from android studio? You can follow the instructions for building tangram native library for android here: https://github.com/tangrams/tangram-es#android

**Comment by blair1618** [comment]
This issue should be resolved by following the full build process in the README, so I'll go ahead and close it.

**Comment by kkalera** [comment]
Hey @blair1618 and @tallytalwar,

I did not build the native app before opening it in Android studio. I just cloned the repo from github and opened the demo project in Android studio. 

I will try to build it first, when i can. Sorry for the late response, I'm having quite a busy schedule lately.
